In [19]:
import numpy as np

In [20]:
actual_values = np.array([100, 150, 200, 250])
predicted_values = np.array([90, 140, 180, 270])
mae=np.mean(abs(actual_values-predicted_values))
print('MAE=', mae)

MAE= 15.0


In [21]:
mse=np.mean((actual_values-predicted_values)**2)
print('MSE=', mse)

MSE= 250.0


# Анализ результатов

Сернеквадратичная ошибка MSE=250 довольно высокая. Т.е данные не сбалансированы и тмеют довольно много выбрасов. Поэтому модель имеет плохую большую метрику MSE. Необходимо усложнять модель, а лучше добавить дополнительные признки для сгаживания выбрасов.

MAE=15.0 уже поменьше, но не так высока как MSE.

Впиринципе модель удовлетворительно описывает поведение данных около среднего значения судя по значению MAE=15, но плохо описывает разбросы в данных судя по высокому MSE=250. Разброс в данных очень велик из-за недостатка данных. Нужны дополнительные данные или же дополнительные признаки. Также можно усложнить модель.

При выполнении этих действий можно снизить MAE и MSE.